import { StyleSheet } from "react-native";
import {
  FONT_FAMILY_REGULAR,
  GREY_COLOR_CODE,
  WHITE_COLOR_CODE,
  SMALL_TEXT_COLOR_CODE,
  LINE_COMMON_COLOR_CODE,
  YELLOW_COLOR_CODE,
  BLACK_COLOR_CODE,
  FONT_FAMILY_BOLD,
  LIGHT_BLACK_COLOR_CODE,
  FONT_FAMILY_LIGHT,
  LIGHT_WHITE_COLOR,
  LIGHT_GREY_COLOR_CODE,
} from "../../../Utils/Constant";
const Styles = StyleSheet.create({
  HeaderView: {
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 10,
  },
  HeaderMiddleCon: {
    flex: 2.5,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  MainHeadTxt: {
    fontFamily: FONT_FAMILY_BOLD,
    fontSize: 20,
    lineHeight: 23,
    color: WHITE_COLOR_CODE,
  },
  HeaderRightView: {
    flex: 2.5,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  headericon: {
    marginRight: 10,
    height: 25,
    width: 25,
  },
  hdngtxt: {
    fontSize: 18,
    lineHeight: 20,
    fontFamily: FONT_FAMILY_REGULAR,
    color: "#3a3838",
    marginTop: 10,
  },
  jobTitle: {
    fontSize: 15,
    lineHeight: 18,
    fontFamily: FONT_FAMILY_REGULAR,
    color: "#3a3838",
  },
  dataCon: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    paddingLeft: 5,
    borderBottomWidth: 0.3,
    borderColor: "lightgrey",
  },
  text: {
    color: SMALL_TEXT_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 12,
    lineHeight: 14,
    marginVertical: 2,
  },
  posterimg: {
    width: 115,
    height: 115,
    borderRadius: 15,
    borderWidth: 0.2,
    borderColor: "grey",
    alignItems: "center",
    marginHorizontal: 5,
  },
  basiccon: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 2,
  },
  icon: {
    height: 15,
    width: 15,
    margin: 2,
    marginLeft: 0,
    marginRight: 5,
  },
  AnyKeywordView: {
    backgroundColor: WHITE_COLOR_CODE,
    padding: 20,
    borderWidth: 1,
    marginLeft: 15,
    marginRight: 15,
    marginTop: 10,
    borderRadius: 3,
    borderColor: LINE_COMMON_COLOR_CODE,
    borderColor: "#f2f2f2",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  MainBtnText: {
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 19,
  },
  HeaderArrow: {
    flex: 1.5,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: 10,
  },
  HeaderViewMidle: {
    flex: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  HeaderMiddleTxt: {
    color: WHITE_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
    fontSize: 18,
  },
  FilterImgeView: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  PriceRangeView: {
    padding: 15,
    borderTopColor: LINE_COMMON_COLOR_CODE,
    borderTopWidth: 10,
    borderBottomColor: LINE_COMMON_COLOR_CODE,
    borderBottomWidth: 10,
  },
  PriceRngetXT: {
    fontSize: 18,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  PriceRngeText: {
    color: GREY_COLOR_CODE,
    fontSize: 15,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  FiltersTgView: {
    padding: 15,
  },
  FilterOptnView: {
    backgroundColor: YELLOW_COLOR_CODE,
    width: 120,
    marginTop: 10,
    height: 50,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  FiltersText: {
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 12,
    color: BLACK_COLOR_CODE,
  },
  detailsVw: {
    flex: 1,
    paddingHorizontal: 5,
    marginRight: 5,
    justifyContent: "center",
  },
  emptyVw: {
    height: 250,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTxt: {
    color: LIGHT_BLACK_COLOR_CODE,
    fontSize: 16,
    fontFamily: FONT_FAMILY_LIGHT,
  },
  searchTxt: {
    marginLeft: 20,
    fontSize: 20,
    fontFamily: FONT_FAMILY_REGULAR,
    marginTop: 10,
  },
  inputVw: {
    backgroundColor: WHITE_COLOR_CODE,
    height: 48,
    borderRadius: 6,
  },
  input: {
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 16,
    color: BLACK_COLOR_CODE,
    paddingLeft: 10,
  },
  filterInputVw: {
    borderRadius: 8,
    borderColor: BLACK_COLOR_CODE,
    borderWidth: 0.8,
    height: 55,
    color: BLACK_COLOR_CODE,
    marginTop: 10,
  },
  filterInputTxt: {
    fontSize: 18,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    left: 12,
  },
  filterInput: {
    marginTop: 0,
    paddingLeft: 10,
    fontSize: 18,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  jobTitleVw: {
    borderWidth: 0.8,
    borderRadius: 6,
    flexGrow: 1,
  },
  jobTitles: {
    paddingVertical: 5,
    marginLeft: 16,
    borderBottomWidth: 0.4,
    borderColor: YELLOW_COLOR_CODE,
    marginTop: 5,
  },
  jobTitleTxt: {
    fontSize: 15,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  filterCon: {
    borderColor: BLACK_COLOR_CODE,
    borderWidth: 1,
    paddingVertical: 5,
    borderRadius: 10,
    marginHorizontal: 12,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  filterVw: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  filterTxt: {
    fontSize: 18,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    paddingHorizontal: 5,
  },
  filterDataVw: {
    paddingVertical: 8,
    paddingLeft: 10,
  },
  filterDataTxt: {
    fontSize: 15,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  filterDatasVw: {
    maxHeight: 250,
    marginHorizontal: 10,
  },
  searchInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: LIGHT_GREY_COLOR_CODE,
    marginTop: 5,
    paddingLeft: 10,
    marginHorizontal: 4,
    color: LIGHT_BLACK_COLOR_CODE,
    fontSize: 16,
    fontFamily: FONT_FAMILY_REGULAR,
    height: 42,
  },
});
export default Styles;
