import { Dimensions, StyleSheet } from "react-native";
import {
  WHITE_COLOR_CODE,
  FONT_FAMILY_BOLD,
  YELLOW_COLOR_CODE,
  LINE_COMMON_COLOR_CODE,
  GREY_COLOR_CODE,
  FONT_FAMILY_REGULAR,
  BLACK_COLOR_CODE,
  LIGHT_GREEN_COLOR_CODE,
  LIGHT_RED_COLOR_CODE,
  LIGHT_BLACK_COLOR_CODE,
  LIGHT_GREY_COLOR_CODE,
  IOS,
  SMALL_TEXT_COLOR_CODE,
  BLUE_COLOR_CODE,
  windowWidth,
  BORDER_LINE_CODE,
} from "../../../../../Utils/Constant";
const { width, height } = Dimensions.get("window");

const Styles = StyleSheet.create({
  topHeaderVw: {
    justifyContent: "space-between",
    paddingHorizontal: 6,
    paddingVertical: IOS ? 30 : 4,
  },
  topHeaderTxt: {
    fontSize: 18,
    color: WHITE_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  backImgVw: {
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: 30,
    paddingHorizontal: 35,
  },
  mainTxt: {
    fontSize: 30,
    color: WHITE_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
    marginRight: 28,
    textTransform: "capitalize",
  },
  mainContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: WHITE_COLOR_CODE,
    marginVertical: 4,
  },
  titletxt: {
    fontSize: 20,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  subTitleTxt: {
    fontSize: 18,
    color: LIGHT_RED_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
  },
  smallTxt: {
    fontSize: 16,
    color: GREY_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
    top: 1,
  },
  smallOptionVw: {
    backgroundColor: LINE_COMMON_COLOR_CODE,
    borderRadius: 100,
    padding: 8,
    marginHorizontal: 20,
    marginVertical: 5,
  },
  smallOptiontxt: {
    fontSize: 15,
    fontFamily: FONT_FAMILY_REGULAR,
    color: BLACK_COLOR_CODE,
    width: 80,
    textAlign: "center",
  },
  longTxt: {
    fontSize: 20,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
    textAlign: "center",
  },
  smallCon: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    marginVertical: 8,
    marginHorizontal: 10,
    backgroundColor: LINE_COMMON_COLOR_CODE,
    borderRadius: 12,
  },
  smallOptiontxt2: {
    fontSize: 16,
    fontFamily: FONT_FAMILY_REGULAR,
    color: BLACK_COLOR_CODE,
  },
  buttonsVw: {
    alignItems: "center",
    flexDirection: "row",
    borderColor: GREY_COLOR_CODE,
    borderBottomWidth: 0.5,
    paddingVertical: 8,
    marginHorizontal: 20,
    justifyContent: "space-between",
    marginVertical: 10,
  },
  buttonsTxt: {
    fontSize: 20,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    marginLeft: 8,
  },
  sectionTxt: {
    fontSize: 25,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
  },
  tapButtonsVw: {
    backgroundColor: WHITE_COLOR_CODE,
    elevation: 2,
    alignItems: "center",
    paddingVertical: 12,
    marginTop: 10,
  },
  considrVw: {
    marginVertical: 5,
    borderBottomWidth: 0.6,
    borderColor: GREY_COLOR_CODE,
    paddingHorizontal: 6,
    paddingVertical: 10,
  },
  considrTxt: {
    fontSize: 22,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
  },
  considrImgVw: {
    width: 34,
    height: 34,
    borderRadius: 100,
    backgroundColor: LINE_COMMON_COLOR_CODE,
    marginRight: 12,
  },
  considrTxtVw: {
    fontSize: 16,
    fontFamily: FONT_FAMILY_REGULAR,
    color: SMALL_TEXT_COLOR_CODE,
    lineHeight: 20,
    width: "90%",
  },
  blueColorTxt: {
    fontSize: 16,
    fontFamily: FONT_FAMILY_REGULAR,
    color: BLUE_COLOR_CODE,
  },
  photoImgVw: {
    width: windowWidth / 1.8,
    height: 120,
    marginRight: 12,
  },
  tapRowButtonsVw: {
    backgroundColor: WHITE_COLOR_CODE,
    elevation: 2,
    alignItems: "center",
    paddingVertical: 12,
    justifyContent: "space-between",
    flexDirection: "row",
    paddingHorizontal: 16,
  },
  timingVw: {
    marginVertical: 12,
  },
  posterVw: {
    flex: 1,
    borderColor: BLACK_COLOR_CODE,
  },
  dotActiveVw: {
    borderRadius: 100,
    backgroundColor: YELLOW_COLOR_CODE,
    width: 16,
    height: 16,
  },
  dotInActiveVw: {
    borderRadius: 100,
    backgroundColor: BLACK_COLOR_CODE,
    width: 20,
    height: 20,
  },

  moreInfoTxt: {
    textAlign: "center",
    fontSize: 20,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    marginRight: 50,
    flex: 1,
  },
  popularCardTouch: {
    // backgroundColor: "red",
    padding: 10,
    margin: 5,
    width: 130,
    height: 180,
    shadowColor: "#000",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    borderRadius: 5,
    borderColor: BORDER_LINE_CODE,
    // backgroundColor: BORDER_LINE_CODE,
    borderWidth: 1,
  },
  popularimage: {
    height: 100,
    width: 120,
    alignSelf: 'center',
    resizeMode: 'cover'
  },
  popularNameTxt:{
    fontSize: 18,
    fontFamily: FONT_FAMILY_REGULAR,
    color: BLACK_COLOR_CODE,
    marginTop: 10
  },
  popularPrice:{
    fontSize: 18,
    fontFamily: FONT_FAMILY_REGULAR,
    color: BLACK_COLOR_CODE,
  },
});
export default Styles;
