import { StyleSheet } from "react-native";
import {
  COLORS,
  Constants,
  FONT_FAMILY,
  FONT_SIZE,
} from "../../../../../Utils/Constant";

const Styles = StyleSheet.create({
  topHeaderVw: {
    justifyContent: "space-between",
    paddingHorizontal: 6,
    paddingVertical: Constants.Ios ? 10 : 4,
  },
  topHeaderTxt: {
    fontSize: FONT_SIZE.mediumL,
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  backImgVw: {
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: 30,
    paddingHorizontal: 35,
  },
  mainTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.BOLD,
    marginRight: 28,
    textTransform: "capitalize",
  },
  mainContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: COLORS.WHITE,
    marginVertical: 4,
  },
  titletxt: {
    fontSize: FONT_SIZE.medium,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  subTitleTxt: {
    fontSize: FONT_SIZE.smallL,
    color: COLORS.LIGHT_RED,
    fontFamily: FONT_FAMILY.BOLD,
  },
  smallTxt: {
    fontSize: FONT_SIZE.smallL,
    color: COLORS.GREY,
    fontFamily: FONT_FAMILY.BOLD,
    top: 1,
  },
  smallOptionVw: {
    backgroundColor: COLORS.COMMON,
    borderRadius: 100,
    padding: 8,
    marginHorizontal: 20,
    marginVertical: 5,
  },
  onSaved: {
    borderColor: COLORS.YELLOW,
    borderWidth: 1,
    backgroundColor: COLORS.WHITE,
  },
  smallOptiontxt: {
    fontSize: FONT_SIZE.normal,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    // width: 80,
    textAlign: "center",
  },
  longTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
    textAlign: "center",
  },
  smallCon: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    marginVertical: 8,
    marginHorizontal: 10,
    backgroundColor: COLORS.COMMON,
    borderRadius: 12,
  },
  smallOptiontxt2: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
  },
  buttonsVw: {
    alignItems: "center",
    flexDirection: "row",
    borderColor: COLORS.BORDER_LINE,
    borderBottomWidth: Constants.normalBW,
    paddingVertical: 8,
    marginHorizontal: 10,
    justifyContent: "space-between",
    // marginVertical: 10,
  },
  buttonsTxt: {
    fontSize: FONT_SIZE.medium,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
    marginLeft: 8,
  },
  sectionTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
  },
  tapButtonsVw: {
    backgroundColor: COLORS.WHITE,
    elevation: 2,
    alignItems: "center",
    paddingVertical: 12,
    marginTop: 10,
  },
  considrVw: {
    marginVertical: 5,
    borderBottomWidth: Constants.normalBW,
    borderColor: COLORS.BORDER_LINE,
    paddingHorizontal: 6,
    paddingVertical: 10,
  },
  considrTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
  },
  considerView: {
    flex: 1,
  },
  considrHeadingTxt: {
    fontSize: FONT_SIZE.medium,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
  },
  considrImgVw: {
    width: 40,
    height: 40,
    borderRadius: 100,
    marginRight: 12,
  },
  considrTxtVw: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.SMALL_TEXT,
    lineHeight: 20,
    width: "90%",
  },
  considerImage: {
    height: 100,
    width: 100,
    borderRadius: 10,
    marginRight: 10,
  },
  msgWrap: {},
  msgView: {
    borderWidth: Constants.standardBW,
    borderColor: COLORS.GREY,
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 20,
    marginBottom: 10,
    backgroundColor: COLORS.LIGHT_WHITE
  },
  msgTxt: {
    fontSize: FONT_SIZE.smallL,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  inputView: {
    flexDirection :'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    borderRadius: 10,
    borderWidth: Constants.standardBW,
  },
  inputstyle: {
    width: '80%',
    fontSize: FONT_SIZE.smallL,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  blueColorTxt: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLUE,
  },
  photoImgVw: {
    width: Constants.windowWidth / 1.8,
    height: 120,
    marginRight: 12,
  },
  tapRowButtonsVw: {
    backgroundColor: COLORS.WHITE,
    elevation: 2,
    alignItems: "center",
    paddingVertical: 12,
    justifyContent: "space-between",
    flexDirection: "row",
    paddingHorizontal: 16,
  },
  timingVw: {
    marginVertical: 12,
  },
  moreInfoTxt: {
    textAlign: "center",
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
    marginRight: 50,
    flex: 1,
  },
  popularCardTouch: {
    // backgroundColor: "red",
    padding: 10,
    margin: 5,
    width: 130,
    height: 180,
    shadowColor: "#000",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 2,
    borderRadius: 5,
    borderColor: COLORS.BORDER_LINE,
    // backgroundColor: BORDER_LINE_CODE,
    borderWidth: Constants.normalBW,
  },
  popularimage: {
    height: 100,
    width: 120,
    alignSelf: "center",
    resizeMode: "cover",
  },
  popularNameTxt: {
    fontSize: FONT_SIZE.mediumL,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    marginTop: 10,
  },
  popularPrice: {
    fontSize: FONT_SIZE.smallL,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
  },
  highlightsView: {
    flex: 1,
    // justifyContent: "center",
    alignItems: "center",
    padding: 10,
  },
  highlightsImage: {
    height: 50,
    width: 50,
  },
  highlightsText: {
    textAlign: "center",
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    width: "100%",
    // backgroundColor: 'red',
  },
  availJobsView: {
    margin: 5,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.BORDER_LINE,
  },
  availjobsImage: {
    height: 60,
    width: 60,
    borderRadius: 7,
  },
  availJobstxt: {
    fontSize: FONT_SIZE.mediumL,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    marginBottom: 10,
  },
  availJobsExptxt: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    marginLeft: 10,
  },
  jobHeadingView: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  locationView: {
    flexDirection: "row",
    marginTop: 10,
  },
  availJobslocationTxt: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    marginLeft: 10,
  },

  eventsImage: {
    height: 200,
    width: 150,
    backgroundColor: COLORS.BLACK,
    borderRadius: 10,
  },
  eventsView: {
    margin: 10,
  },
  eventheadingView: {
    flex: 1,
    alignItems: "center",
    marginTop: 10,
  },
  eventsheadignTxt: {
    fontSize: FONT_SIZE.large,
    fontFamily: FONT_FAMILY.BOLD,
    color: COLORS.WHITE,
    textAlign: "center",
  },
  eventknowTouch: {
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
    padding: 10,
    borderWidth: 2,
    borderColor: COLORS.WHITE,
    borderRadius: 10,
  },
  knowTxt: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.BOLD,
    color: COLORS.WHITE,
    // marginLeft: 10,
    textAlign: "center",
  },
  mainConatiner: {
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderColor: COLORS.GREY_COLOR_CODE,
  },
  largeImgVw: {
    width: 110,
    height: 120,
    borderRadius: 15,
    marginBottom: 5,
  },
  straightVw: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 4,
  },
  rowVw: {
    flexDirection: "row",
    marginVertical: 4,
  },
  ratingVw: {
    backgroundColor: "#a3d74e",
    paddingHorizontal: 5,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 3,
    marginRight: 5,
  },
  ratingTxt: {
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.BOLD,
    fontSize: FONT_SIZE.medium,
  },
  businessNameInDetailTxt: {
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
    fontSize: FONT_SIZE.mediumL,
  },
  innContainer: {
    flex: 1,
    paddingHorizontal: 10,
  },
  infoView: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 2,
  },
  largeNameTxt: {
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: 18,
    color: COLORS.BLACK,
    textTransform: "capitalize",
  },
  emptyConVw: {
    height: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyConTxt: {
    fontSize: 18,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  lightTxt: {
    fontSize: 14,
    color: COLORS.SMALL_TEXT,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  smallImgVw: {
    width: 35,
    height: 35,
    borderRadius: 100,
    marginHorizontal: 5,
    marginLeft: 10,
    marginTop: 10,
  },
  postImageStyle: {
    width: 380,
    height: 200,
    borderRadius: 10,
    marginHorizontal: 5,
    marginLeft: 10,
    marginTop: 10,
  },
  businessCategoryTxt: {
    fontSize: FONT_SIZE.smallL,
    // color: COLORS.SMALL_TEXT,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  considerTouch: {
    width: "100%",
    backgroundColor: COLORS.YELLOW,
    alignItems: "center",
    padding: 5,
    borderRadius: 10,
    marginTop: 10,
  },
  considerBtnTxt: {
    fontSize: FONT_SIZE.mediumL,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  businessAddressTxt: {
    fontSize: FONT_SIZE.small,
    color: COLORS.SMALL_TEXT,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  uploadBtn: {
    marginBottom: 20,
    borderRadius: 10,
    width: "50%",
  },
  uploadBtnTxt: {
    fontSize: FONT_SIZE.medium,
    color: COLORS.SMALL_TEXT,
    fontFamily: FONT_FAMILY.BOLD,
  },
  previewImage: {
    flex: 1,
    margin: 50,
    borderRadius: 10,
  },
  headlineTxt: {
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.NORMAL_BOLD,
    fontSize: FONT_SIZE.medium,
  },
  descriptionTxt: {
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.smallL,
  },
  nullTxt: {
    color: COLORS.BLUE,
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.smallL,
    marginTop: 10,
  },
  reservTxt: {
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.smallL,
  },
  btnTextCenter: { color: COLORS.GREY, textAlign: "center" },
});
export default Styles;
