import { StyleSheet } from "react-native";
import {
  COLORS,
  Constants,
  FONT_FAMILY,
  FONT_SIZE,
} from "../../../../../Utils/Constant";

const Styles = StyleSheet.create({
  topHeaderVw: {
    justifyContent: "space-between",
    paddingHorizontal: 6,
    paddingVertical: Constants.Ios ? 10 : 4,
  },
  topHeaderTxt: {
    fontSize: FONT_SIZE.mediumL,
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  backImgVw: {
    flex: 1,
    justifyContent: "flex-end",
    paddingBottom: 30,
    paddingHorizontal: 35,
  },
  mainTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.BOLD,
    marginRight: 28,
    textTransform: "capitalize",
  },
  mainContainer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: COLORS.WHITE,
    marginVertical: 4,
  },
  titletxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  subTitleTxt: {
    fontSize: FONT_SIZE.mediumL,
    color: COLORS.LIGHT_RED,
    fontFamily: FONT_FAMILY.BOLD,
  },
  smallTxt: {
    fontSize: FONT_SIZE.medium,
    color: COLORS.GREY,
    fontFamily: FONT_FAMILY.BOLD,
    top: 1,
  },
  smallOptionVw: {
    backgroundColor: COLORS.COMMON,
    borderRadius: 100,
    padding: 8,
    marginHorizontal: 20,
    marginVertical: 5,
  },
  smallOptiontxt: {
    fontSize: FONT_SIZE.normal,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    width: 80,
    textAlign: "center",
  },
  longTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
    textAlign: "center",
  },
  smallCon: {
    paddingHorizontal: 20,
    paddingVertical: 8,
    marginVertical: 8,
    marginHorizontal: 10,
    backgroundColor: COLORS.COMMON,
    borderRadius: 12,
  },
  smallOptiontxt2: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
  },
  buttonsVw: {
    alignItems: "center",
    flexDirection: "row",
    borderColor: COLORS.BORDER_LINE,
    borderBottomWidth: Constants.normalBW,
    paddingVertical: 8,
    marginHorizontal: 20,
    justifyContent: "space-between",
    marginVertical: 10,
  },
  buttonsTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
    marginLeft: 8,
  },
  sectionTxt: {
    fontSize: FONT_SIZE.largeL,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
  },
  tapButtonsVw: {
    backgroundColor: COLORS.WHITE,
    elevation: 2,
    alignItems: "center",
    paddingVertical: 12,
    marginTop: 10,
  },
  considrVw: {
    marginVertical: 5,
    borderBottomWidth: Constants.normalBW,
    borderColor: COLORS.BORDER_LINE,
    paddingHorizontal: 6,
    paddingVertical: 10,
  },
  considrTxt: {
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.BOLD,
  },
  considrImgVw: {
    width: 34,
    height: 34,
    borderRadius: 100,
    backgroundColor: COLORS.COMMON,
    marginRight: 12,
  },
  considrTxtVw: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.SMALL_TEXT,
    lineHeight: 20,
    width: "90%",
  },
  blueColorTxt: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLUE,
  },
  photoImgVw: {
    width: Constants.windowWidth / 1.8,
    height: 120,
    marginRight: 12,
  },
  tapRowButtonsVw: {
    backgroundColor: COLORS.WHITE,
    elevation: 2,
    alignItems: "center",
    paddingVertical: 12,
    justifyContent: "space-between",
    flexDirection: "row",
    paddingHorizontal: 16,
  },
  timingVw: {
    marginVertical: 12,
  },
  moreInfoTxt: {
    textAlign: "center",
    fontSize: FONT_SIZE.large,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
    marginRight: 50,
    flex: 1,
  },
  popularCardTouch: {
    // backgroundColor: "red",
    padding: 10,
    margin: 5,
    width: 130,
    height: 180,
    shadowColor: "#000",
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 2,
    borderRadius: 5,
    borderColor: COLORS.BORDER_LINE,
    // backgroundColor: BORDER_LINE_CODE,
    borderWidth: Constants.normalBW,
  },
  popularimage: {
    height: 100,
    width: 120,
    alignSelf: "center",
    resizeMode: "cover",
  },
  popularNameTxt: {
    fontSize: FONT_SIZE.mediumL,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
    marginTop: 10,
  },
  popularPrice: {
    fontSize: FONT_SIZE.mediumL,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.BLACK,
  },
});
export default Styles;
