export const Images = {
  SPLASH_LOGO: require("../Assets/login_graphic.png"),
  BLACK_LOGO: require("../Assets/Abbypages_black.gif"),
  MAP_LOGO: require("../Assets/abby_pages_map_icon.png"),

  //-------------Important Images-----------------//
  RESTO_LIST_IMG: require("../Assets/restaurant_list_icon.png"),
  JOB_LIST_IMG: require("../Assets/job_list_icon.png"),
  SERVICE_LIST_IMG: require("../Assets/service_list_icon.png"),
  EVENT_LIST_IMG: require("../Assets/event_list_icon.png"),
  SHOPP_LIST_IMG: require("../Assets/shopping_list_icon.png"),
  //-------------Important Images End-----------------//

  //-------------Other Images-----------------//
  ABOUT_IMG: require("../Assets/about_icon_1.png"),
  FAVRT_IMG: require("../Assets/like_icon_filled.png"),
  CLOTH_IMG: require("../Assets/about_icon_3.png"),
  PARKING_IMG: require("../Assets/about_icon_4.png"),
  ACTIVE_SWITCH_IMG: require("../Assets/active_switch.png"),
  UNACTIVE_SWITCH_IMG: require("../Assets/unactive_switch.png"),
  THEME_ADD_IMG: require("../Assets/add_location_icon.png"),
  CAMERA_IMG: require("../Assets/camera_icon_list.png"),
  ADD_PRIMARY_IMG: require("../Assets/add_primary.png"),
  OTHER_ADD_PRIMARY_IMG: require("../Assets/add_primary_icon.png"),
  ARROW_RIGHT_IMG: require("../Assets/arrow_right_icon.png"),
  ARROW_LEFT_IMG: require("../Assets/back_arrow_icon_btn.png"),
  BOOKMARK_IMG: require("../Assets/bookmark_icon_menu.png"),
  OTHER_BOOKMARK_IMG: require("../Assets/bookmark_icon_text.png"),
  PRODUCT_ORDER_IMG: require("../Assets/box.png"),
  UNCHECK_IMG: require("../Assets/unchecked_squared_icon_small.png"),
  CHECK_IMG: require("../Assets/checked_squared_icon_small.png"),
  OTHER_CHECK_IMG: require("../Assets/box_check_white_icon.png"),
  BUSINESS_ADD_1_IMG: require("../Assets/Goals123.png"), //
  BUSINESS_ADD_2_IMG: require("../Assets/Untitled-1.png"),
  BUSINESS_ADD_3_IMG: require("../Assets/Untitled-2.png"),
  BUSINESS_ADD_4_IMG: require("../Assets/loaction.png"),
  BUSINESS_ADD_5_IMG: require("../Assets/Budget11.png"),
  MONEY_IMG: require("../Assets/budget_icon.jpeg"),
  BULB_IMG: require("../Assets/bulb_icon_menu.png"),
  BUSINESS_ADDRS_IMG: require("../Assets/business_address_icon.png"),
  BUSINESS_CALL_IMG: require("../Assets/business_call_icon.png"),
  BUSINESS_INFO_IMG: require("../Assets/businessinformation.png"),
  BUSINESS_MENU_IMG: require("../Assets/business_menu_icon.png"),
  BUSINESS_PROFILE_IMG: require("../Assets/businessprofile.png"),
  BUSINESS_WEBSITE_IMG: require("../Assets/business_website_icon.png"),
  CALENDER_IMG: require("../Assets/calendar_icon.png"), //also work on calendar_icon_field.png image
  COLORED_CAMERA_IMG: require("../Assets/camera.png"),
  COLORED_CANCEL_IMG: require("../Assets/cancelModalBtn.png"),
  CANCEL_IMG: require("../Assets/cart_delete_icon.png"),
  CART_ADDED_IMG: require("../Assets/cart_icon_header.png"),
  CASHBACK_IMG: require("../Assets/cash_back_icon.png"),
  DOLLAR_IMG: require("../Assets/cash_back_icon_menu.png"),
  THEME_CHECK_IMG: require("../Assets/checked_box.png"),
  THEME_UNCHECK_IMG: require("../Assets/uncheck_box.png"),
  ROUND_CHECK_IMG: require("../Assets/checked_circled_icon_box.png"),
  ROUND_UNCHECK_IMG: require("../Assets/unchecked_circled_icon_box.png"),
  ROUNDWHITE_CHECK_IMG: require("../Assets/check_icon_info_small.png"),
  CHECK_IN_IMG: require("../Assets/checkin_icon_menu.png"),
  CHECKOUT_PAY_IMG: require("../Assets/checkout_payment_icon.png"),
  CLOCK_IMG: require("../Assets/clock_icon.png"),
  CHECKOUT_SCHDULD_IMG: require("../Assets/checkout_scheduled_icon.png"),
  CHECKOUT_USER_IMG: require("../Assets/checkout_user_icon.png"),
  COLLECTION_IMG: require("../Assets/collection_icon_menu.png"),
  COMMENT_IMG: require("../Assets/comment_icon.png"),
  CONSUMER_IMG: require("../Assets/company_consumer_icon.png"),
  COMPANY_DEFAULT_IMG: require("../Assets/company_default_icon.png"),
  THEME_COMPANY_DEFAULT_IMG: require("../Assets/company_default_photo.png"),
  COMPANY_REVIEW_IMG: require("../Assets/company_reviews_icon.png"),
  CONFIRM_S__IMG: require("../Assets/confirm_s_icon_1.png"),
  CONFIRM_THUNDER_IMG: require("../Assets/confirm_s_icon_4.png"),
  DASHBOARD_IMG: require("../Assets/dashboardicon.png"),
  DEFAULT_BOX_IMG: require("../Assets/default_image_box.png"),
  DIET_IMG: require("../Assets/diet.png"),
  DINEOUT_IMG: require("../Assets/dine_out_icon.png"),
  DINEER_IMG: require("../Assets/dinner.png"),
  DASHBOARDHOME_IMG: require("../Assets/drawerhome.png"),
  EVENT_IMG: require("../Assets/events_icon_menu.png"),
  ARROW_DOWN_IMG: require("../Assets/link_dropdown_ico.png"),//use another color for color change
  ARROW_UP_IMG: require("../Assets/link_dropdown_icon_up.png"),///use another color for color change
  EDIT_PENCIL_IMG: require("../Assets/edit_pencil_icon.png"),//use YELLOW_COLOR_CODE color for background
  EDIT_PHOTO_IMG: require("../Assets/edit_photo_icon.png"),
  EMPLOYESS_IMG: require("../Assets/employeeonboard.png"),
  ENVELOPE_IMG: require("../Assets/envelope_icon_menu.png"),
  ERROR_IMG: require("../Assets/Error.png"),
  FILTER_IMG: require("../Assets/filter_icon.png"),
  FINAL_ORDER_IMG: require("../Assets/final_order.png"),
  FINAL_ORDERDOT_IMG: require("../Assets/final_order1.png"),
  FIRE_IMG: require("../Assets/fire_icon.png"),
  FOLLOWER_IMG: require("../Assets/followers_icon_menu.png"),
  FOLLOWING_IMG: require("../Assets/following_icon_menu.png"),
  FRIENDS_IMG: require("../Assets/friends_info_graphic.png"),
  WHITE_ARROW_IMG: require("../Assets/Group1672.png"),
  DRAWER_IMG: require("../Assets/hamburger_icon.png"),
  HEADER_BCK_IMG: require("../Assets/header_back_btn.png"),
  HEADPHONES_IMG: require("../Assets/headphones_icon_box.png"),
  HIGHLIGHT_1_IMG: require("../Assets/highlight_icon_1.png"),
  HIGHLIGHT_2_IMG: require("../Assets/highlight_icon_2.png"),
  HIGHLIGHT_3_IMG: require("../Assets/highlight_icon_3.png"),
  HIGHLIGHT_4_IMG: require("../Assets/highlight_icon_4.png"),
  HIGHLIGHT_5_IMG: require("../Assets/highlight_icon_5.png"),
  HIGHLIGHT_6_IMG: require("../Assets/highlight_icon_6.png"),
  GALLERY_IMG: require("../Assets/image-gallery.png"),
  CALL_IMG: require("../Assets/info_call_icon.png"),
  GLOBE_IMG: require("../Assets/info_globe_icon.png"),
  INFO_IMG: require("../Assets/info_icon_circled.png"),
  THEME_INFO_IMG: require("../Assets/info_icon_large.png"),
  LOCATION_IMG: require("../Assets/info_marker_icon.png"),
  THUMB_IMG: require("../Assets/thumb_icon.png"),
  LIMITED_IMG: require("../Assets/limited.png"),
  DELETE_IMG: require("../Assets/list_delete_icon.png"),
  LIST_IMG: require("../Assets/listmenucopy.png"),
  THEME_LOCATION_IMG: require("../Assets/Location_icon.png"),
  CIRCLE_LOCATION_IMG: require("../Assets/Location_icon_small.png"),
  LOCK_IMG: require("../Assets/lock_icon_menu.png"),
  GRAPHIC_LOGO_IMG: require("../Assets/login_graphic2.png"),
  MIDDLE_LOGO_IMG: require("../Assets/login_logo.png"),
  MANAGE_IMG: require("../Assets/management.png"),
  MAP_LIST_IMG: require("../Assets/map_list_icon.png"),
  EMPTY_IMG: require("../Assets/MaskGroup25.png"),
  LOGOUT_IMG: require("../Assets/menu-logout-icon.png"),
  METER_IMG: require("../Assets/meter.png"),
  MINUS_IMG: require("../Assets/minus_icon_cart.png"),
  MONEY_NOTE_IMG: require("../Assets/money_icon.png"),
  NOTIFICATION_IMG: require("../Assets/notification.png"),
  HOURS_IMG: require("../Assets/openinghours.png"),
  ORDERS_IMG: require("../Assets/order_icon_box_large.png"),
  ORDERLIST_IMG: require("../Assets/order_icon_menu.png"),
  PLUS_IMG: require("../Assets/plus_icon_header.png"),
  PRIVACY_IMG: require("../Assets/privacy_icon_menu.png"),
  PROCEED_IMG: require("../Assets/processed.jpg"),
  DEFAULT_IMG: require("../Assets/profile_photo_default_circled.png"),
  PROJECT_IMG: require("../Assets/project_icon.png"),
  QTY_MINUS_IMG: require("../Assets/qty_minus_icon3.png"),
  QTY_PLUS_IMG: require("../Assets/qty_plus_icon.png"),
  RADIO_CHECK_IMG: require("../Assets/radio_circled_checked.png"),
  RADIO_UNCHECK_IMG: require("../Assets/radio_circled_unchecked.png"),
  RECENT_IMG: require("../Assets/recent_activity.png"),
  REVIEWED_IMG: require("../Assets/review_graphic.png"),
  SAVED_IMG: require("../Assets/save_icon.png"),
  SEARCH_IMG: require("../Assets/search_field_icon.png"),
  SETTING_IMG: require("../Assets/settings_icon_menu.png"),
  SHARE_IMG: require("../Assets/share_icon.png"),
  SQUARE_IMG: require("../Assets/squares.png"),
  STAR_IMG: require("../Assets/star_icon.png"),
  STAR_FILLED_IMG: require("../Assets/star_icon_filled.png"),
  STAR_UNFILLED_IMG: require("../Assets/star_icon_text.png"),
  THEME_GOALS_IMG: require("../Assets/st_icon_1.png"),
  THEME_CALL_IMG: require("../Assets/st_icon_2.png"),
  THEME_PC_IMG: require("../Assets/st_icon_3.png"),
  THEME_KEYBOARD_IMG: require("../Assets/st_icon_4.png"),
  THEME_HOME_IMG: require("../Assets/st_icon_5.png"),
  THEME_GO_IMG: require("../Assets/st_icon_6.png"),
  THEME_FEATURE_IMG: require("../Assets/st_icon_7.png"),
  THEME_HOURS_IMG: require("../Assets/st_icon_8.png"),
  THEME_SPECIAL_HR_IMG: require("../Assets/st_icon_9.png"),
  THEME_SPECIALIST_IMG: require("../Assets/st_icon_10.png"),
  THEME_HISTORY_IMG: require("../Assets/st_icon_11.png"),
  THEME_INTRO_IMG: require("../Assets/st_icon_12.png"),
  THEME_PHOTOS_IMG: require("../Assets/st_icon_13.png"),
  THEME_SLIDES_IMG: require("../Assets/st_icon_14.png"),
  THEME_ACTION_IMG: require("../Assets/st_icon_15.png"),
  THEME_STAR_HOME_IMG: require("../Assets/st_icon_16.png"),
  THEME_LOCATION_IMG: require("../Assets/st_icon_17.png"),
  THEME_IN_IMG: require("../Assets/st_icon_18.png"),
  THEME_PHONE_IMG: require("../Assets/st_icon_19.png"),
  THEME_SEARCH_IMG: require("../Assets/st_icon_20.png"),
  SUCCESS_IMG: require("../Assets/Success_yellow.png"),
  MANAGE_JOB_IMG: require("../Assets/teamwork.png"),
  TICK_IMG: require("../Assets/text_check_icon.png"),
  TRASH_IMG: require("../Assets/trash_icon_header.png"),
  THEME_UPLOAD_IMG: require("../Assets/upload_icon_box.png"),
  UPLOAD_IMG: require("../Assets/upload_icon_field.png"),
  PROFILE_IMG: require("../Assets/user_icon_text.png"),
  THEME_PROFILE_IMG: require("../Assets/user_icon_box_large.png"),
  VERIFIED_IMG: require("../Assets/verified_icon.png"),
  VERIFIED_BLUE_IMG: require("../Assets/verified_img.png"),
  VIEW_EYE_IMG: require("../Assets/viewed_icon.png"),
  PRIMARY_IMG: require("../Assets/add_primary_icon_color.png"),
  CAP_SUCCESS_IMG: require("../Assets/success_icon.png"),
};
//delete
//map_field_icon.png on LOCATION_IMG
//list_guest_icon.png on PROFILE_IMG
//profile_icon_menu.png on PROFILE_IMG
//confirm_s_icon_2.png on CHECKOUT_PAY_IMG
//confirm_s_icon_3.png on CLOCK_IMG
//map_marker_icon.png on on PROFILE_IMG
//musical-sign-of-one-dots.png text added of dot
//info_calendar_icon.png on CALENDER_IMG
//business_chevron_icon.png on ARROW_RIGHT_IMG
