import { StyleSheet } from "react-native";
import {
  WHITE_COLOR_CODE,
  FONT_FAMILY_REGULAR,
  FONT_FAMILY_BOLD,
  BLACK_COLOR_CODE,
  LIGHT_BLACK_COLOR_CODE,
} from "../../../Utils/Constant";
const Styles = StyleSheet.create({
  container: {
    height: 60,
    borderColor: "#d8d8d8",
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: "row",
    margin: 10,
    marginLeft: 15,
    marginRight: 15,
  },
  privacyCon: {
    height: 50,
    borderColor: "#d8d8d8",
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: "row",
    marginHorizontal: 15,
    marginVertical: 8,
    alignItems: "center",
  },
  textInput: {
    fontSize: 18,
    paddingLeft: 20,
    marginLeft: 4,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  CameraImgView: {
    flex: 5,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 15,
  },
  AddPhotosTxt: {
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 17,
    paddingLeft: 10,
  },
  BckArrowBack: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  addressInputVw: {
    textInputContainer: {
      borderRadius: 4,
      backgroundColor: WHITE_COLOR_CODE,
      fontSize: 16,
      marginHorizontal: 17,
      margin: 8,
      fontFamily: FONT_FAMILY_REGULAR,
      borderColor: "#d8d8d8",
      borderRadius: 8,
      borderWidth: 1,
      alignItems: "center",
      paddingVertical: 6,
    },
    textInput: {
      color: BLACK_COLOR_CODE,
      marginLeft: 16,
      fontFamily: FONT_FAMILY_REGULAR,
      fontSize: 17,
    },
    listView: {
      width: "90%",
      alignSelf: "center",
      backgroundColor: WHITE_COLOR_CODE,
    },
  },
  MainContainer: {
    backgroundColor: WHITE_COLOR_CODE,
    paddingTop: 15,
    paddingBottom: 15,
  },
  profileModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  modalItem: {
    fontFamily: FONT_FAMILY_REGULAR,
    textAlign: "center",
    fontSize: 17,
  },
  ktchimgvwe: {
    flexDirection: "row",
    borderRadius: 8,
    height: 55,
    borderColor: "#d8d8d8",
    borderWidth: 1,
    marginBottom: 5,
    marginTop: 15,
    width: "90%",
    alignSelf: "center",
    paddingTop: 15,
    paddingLeft: 12,
  },
  ktchnlble: {
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 15,
  },
  alertBox: {
    width: 200,
    height: 50,
    flexDirection: "row",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(100,100,100, 0.5)",
  },
  alertBackground: {
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
    margin: 10,
    borderRadius: 5,
    paddingVertical: 50,
    backgroundColor: "#f2f2f2",
  },
  plseslecttxt: {
    fontSize: 15,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  profileModal: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },

  moadlvwe: {
    width: "100%",
    marginLeft: 14,
    marginRight: 14,
    height: "100%",
  },
  headervwe: {
    borderBottomWidth: 0.8,
    borderBottomColor: "green",
    flexDirection: "row",
    height: 50,
    flexDirection: "row",
  },
  arealstvwe: {
    flex: 4,
    justifyContent: "center",
    alignItems: "center",
  },
  arealsttxt: {
    fontFamily: FONT_FAMILY_BOLD,
    fontSize: 15,
    color: BLACK_COLOR_CODE,
  },
  cancelbtnimgvwe: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  cancelimg: {
    width: 20,
    height: 20,
    marginTop: 8,
  },
  imagesVw: {
    width: 120,
    height: 120,
    margin: 5,
  },
  deleteImageVw: {
    width: 20,
    height: 20,
    borderRadius: 20,
    position: "absolute",
    zIndex: 9,
    right: 5,
  },
  deleteImage: {
    width: 24,
    height: 24,
    marginTop: 5,
  },
  eventImg: {
    width: 120,
    height: 120,
    borderRadius: 10,
  },
  categoryItemVw: {
    flex: 1,
    borderBottomWidth: 0.3,
    borderBottomColor: "#f2f2f2",
    padding: 10,
    paddingVertical: 15,
    marginHorizontal: 15,
  },
  categoryItemTxt: {
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 15,
    color: BLACK_COLOR_CODE,
  },
  radioBttnVw: {
    marginHorizontal: 15,
    padding: 8,
  },
  radioBttnTxt: {
    fontSize: 18,
    fontFamily: FONT_FAMILY_REGULAR,
    color: BLACK_COLOR_CODE,
  },
  radioBttnCon: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  radioInnerCon: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 5,
  },
  radioImg: {
    width: 18,
    height: 18,
    marginRight: 5,
  },
  radioInnerTxt: {
    fontSize: 15,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  headingTxt: {
    fontSize: 15,
    color: LIGHT_BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  titlesTxt: {
    fontSize: 18,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    marginHorizontal: 20,
    marginTop: 5,
  },
  formsInputCon: {
    borderColor: "#d8d8d8",
    borderWidth: 1,
    borderRadius: 9,
    margin: 8,
    marginLeft: 15,
    marginRight: 15,
    paddingVertical: 4,
  },
  formsInputVw: {
    height: 30,
    paddingTop: 0,
    marginBottom: 8,
    marginLeft: 4,
    fontFamily: FONT_FAMILY_REGULAR,
  },
  straightVw: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    marginLeft: 5,
    paddingBottom: 8,
    bottom: 5,
  },
  moreOptionTxt: {
    fontSize: 14,
    color: BLACK_COLOR_CODE,
    marginLeft: 5,
  },
  datesColumn: {
    flex: 1,
    paddingHorizontal: 10,
    justifyContent: "center",
  },
  datesCon: {
    marginVertical: 10,
    paddingVertical: 15,
    alignItems: "center",
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 0.6,
    marginHorizontal: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    width: "45%",
  },
  nonEditInputVw: {
    height: 35,
    width: "70%",
    borderWidth: 0.6,
    marginVertical: 12,
    borderRadius: 6,
  },
  descriptionVw: {
    height: 58,
    width: "90%",
    borderWidth: 0.5,
    marginVertical: 8,
    borderRadius: 6,
  },
  optionChooseVw: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 9,
    marginVertical: 5,
  },
  checkImg: {
    marginRight: 8,
    width: 24,
    height: 24,
  },
  minMaxVw: {
    height: 45,
    width: "50%",
    borderWidth: 1,
  },
  nonEditTitlesTxt: {
    fontSize: 11,
    color: BLACK_COLOR_CODE,
    fontFamily: FONT_FAMILY_REGULAR,
    marginTop: 5,
  },
  addMoreTckVw: {
    marginTop: 12,
    justifyContent: "center",
  },
});
export default Styles;
