import { Platform, StyleSheet } from "react-native";
import {
  FONT_SIZE,
  FONT_FAMILY,
  COLORS,
} from "../../../../../Utils/Constant";
const Styles = StyleSheet.create({
  HeaderView: {
    justifyContent: "center",
    alignItems: "center",
    paddingLeft: 10,
  },
  HeaderMiddleCon: {
    flex: 2.3,
    justifyContent: "center",
    alignItems: "flex-end",
  },
  MainHeadTxt: {
    fontFamily: FONT_FAMILY.BOLD,
    fontSize: FONT_SIZE.large,
    lineHeight: 23,
    color: COLORS.WHITE,
  },
  HeaderRightView: {
    flex: 2.5,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  headericon: {
    marginRight: 10,
    height: 25,
    width: 25,
    tintColor: COLORS.WHITE,
  },
  topInfoVw: {
    paddingHorizontal: 10,
    paddingVertical: 2,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: COLORS.YELLOW,
  },
  hdngtxt: {
    fontSize: FONT_SIZE.mediumL,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.WHITE,
    padding: 6,
    borderWidth: 1,
    borderColor: COLORS.WHITE,
    borderRadius: 10,
  },
  postJobVW: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 5,
    paddingHorizontal: 5,
  },
  postJobImg: {
    width: 20,
    height: 20,
    resizeMode: "contain",
    marginRight: 8,
  },
  jobTitle: {
    fontSize: FONT_SIZE.smallL,
    lineHeight: 18,
    fontFamily: FONT_FAMILY.REGULAR,
    color: "#3a3838",
  },
  dataCon: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: "row",
    paddingLeft: 5,
    borderBottomWidth: 0.3,
    borderColor: "lightgrey",
  },
  text: {
    color: COLORS.SMALL_TEXT,
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.smallL,
    paddingVertical: 3,
    paddingHorizontal: 3,
  },
  editTxt: {
    color: COLORS.SMALL_TEXT,
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.medium,
  },
  posterimg: {
    width: 115,
    height: 115,
    borderRadius: 15,
    borderWidth: 0.2,
    borderColor: "grey",
    alignItems: "center",
    marginHorizontal: 5,
  },
  basiccon: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 2,
  },
  icon: {
    height: 20,
    width: 20,
    margin: 2,
    marginLeft: 0,
    marginRight: 5,
  },
  AnyKeywordView: {
    backgroundColor: COLORS.WHITE,
    padding: 20,
    borderWidth: 1,
    marginLeft: 15,
    marginRight: 15,
    marginTop: 10,
    borderRadius: 3,
    borderColor: COLORS.COMMON,
    borderColor: COLORS.LIGHT_WHITE,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  MainBtnText: {
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.large,
  },
  HeaderArrow: {
    flex: 1.5,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: 10,
  },
  HeaderViewMidle: {
    flex: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  HeaderMiddleTxt: {
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.BOLD,
    fontSize: FONT_SIZE.mediumL,
  },
  resetVw: {
    paddingHorizontal: 10,
    top: Platform.OS === "ios" ? 5 : 0,
  },
  resetTxt: {
    fontSize: FONT_SIZE.medium,
    color: COLORS.WHITE,
    fontFamily: FONT_FAMILY.BOLD,
  },
  FilterImgeView: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  PriceRangeView: {
    padding: 15,
    borderTopColor: COLORS.COMMON,
    borderTopWidth: 10,
    borderBottomColor: COLORS.COMMON,
    borderBottomWidth: 10,
  },
  PriceRngetXT: {
    fontSize: FONT_SIZE.mediumL,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  PriceRngeText: {
    color: COLORS.GREY,
    fontSize: FONT_SIZE.smallL,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  FiltersTgView: {
    padding: 15,
  },
  FilterOptnView: {
    backgroundColor: COLORS.YELLOW,
    width: 120,
    marginTop: 10,
    height: 50,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  FiltersText: {
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.small,
    color: COLORS.BLACK,
  },
  detailsVw: {
    flex: 1,
    paddingHorizontal: 5,
    marginRight: 5,
    justifyContent: "center",
  },
  emptyVw: {
    height: 250,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTxt: {
    color: COLORS.LIGHT_BLACK,
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.LIGHT,
  },
  searchTxt: {
    marginLeft: 20,
    fontSize: FONT_SIZE.large,
    fontFamily: FONT_FAMILY.REGULAR,
    marginTop: 10,
  },
  inputVw: {
    backgroundColor: COLORS.WHITE,
    height: 48,
    borderRadius: 6,
  },
  input: {
    fontFamily: FONT_FAMILY.REGULAR,
    fontSize: FONT_SIZE.medium,
    color: COLORS.BLACK,
    paddingLeft: 10,
  },
  filterInputVw: {
    borderRadius: 8,
    borderColor: COLORS.BLACK,
    borderWidth: 0.8,
    height: 55,
    marginTop: 10,
  },
  filterInputTxt: {
    fontSize: FONT_SIZE.mediumL,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
    left: 12,
    top: 10,
  },
  filterInput: {
    marginTop: 0,
    paddingLeft: 10,
    fontSize: FONT_SIZE.mediumL,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  jobTitleVw: {
    borderWidth: 0.8,
    borderRadius: 6,
    flexGrow: 1,
  },
  jobTitles: {
    paddingVertical: 5,
    marginLeft: 16,
    borderBottomWidth: 0.4,
    borderColor: COLORS.YELLOW,
    marginTop: 5,
  },
  jobTitleTxt: {
    fontSize: FONT_SIZE.medium,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  filterCon: {
    borderColor: COLORS.BLACK,
    borderWidth: 1,
    paddingVertical: 5,
    borderRadius: 10,
    marginHorizontal: 12,
    paddingHorizontal: 10,
    marginVertical: 10,
  },
  filterVw: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 5,
  },
  filterTxt: {
    fontSize: FONT_SIZE.mediumL,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
    bottom: 12,
    width: "90%",
  },
  filterDataVw: {
    paddingVertical: 12,
    paddingLeft: 10,
    borderBottomWidth: 0.9,
    borderColor: COLORS.YELLOW,
  },
  filterDataTxt: {
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
  },
  selectionModalVw: {
    flex: 1,
    marginTop: Platform.OS === "ios" ? 40 : 5,
    paddingHorizontal: 10,
  },
  filterDatasVw: {
    marginHorizontal: 10,
  },
  searchInput: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.LIGHT_GREY,
    marginTop: Platform.OS === "ios" ? 12 : 5,
    paddingLeft: 10,
    marginHorizontal: 4,
    color: COLORS.LIGHT_BLACK,
    fontSize: FONT_SIZE.medium,
    fontFamily: FONT_FAMILY.REGULAR,
    height: 50,
  },
  typeVw: {
    marginTop: 8,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  typeTxt: {
    fontSize: FONT_SIZE.large,
    fontFamily: FONT_FAMILY.REGULAR,
    color: COLORS.LIGHT_BLACK,
  },
  noDataVw: {
    height: 200,
    alignItems: "center",
    justifyContent: "center",
  },
  noDataTxt: {
    fontSize: FONT_SIZE.mediumL,
    color: COLORS.BLACK,
    fontFamily: FONT_FAMILY.REGULAR,
  },
});
export default Styles;
