import { StyleSheet, Dimensions } from "react-native";
import {
  FONT_FAMILY_REGULAR,
  YELLOW_COLOR_CODE,
  WHITE_COLOR_CODE,
  SMALL_TEXT_COLOR_CODE,
  BLACK_COLOR_CODE,
  FONT_FAMILY_BOLD,
} from "../../../Utils/Constant";
const Styles = StyleSheet.create({
  inputconmn: {
    flexDirection: "row",
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 0,
    height: 60,
    backgroundColor: YELLOW_COLOR_CODE,
    justifyContent: "space-around",
  },
  inputconsmall: {
    backgroundColor: WHITE_COLOR_CODE,
    height: 40,
    width: "80%",
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 5,
    borderRadius: 5,
  },
  filtericonCon: {
    backgroundColor: "#a48400",
    height: 39,
    width: "12%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 5,
  },
  text: {
    fontFamily: FONT_FAMILY_REGULAR,
    color: BLACK_COLOR_CODE,
  },
  productimg: {
    width: "100%",
    height: Dimensions.get("window").height / 5,
    backgroundColor: WHITE_COLOR_CODE,
  },
  flatlistcon: {
    // height: Dimensions.get('window').height / 2,
    height: Dimensions.get("window").height / 2.7,
    width: Dimensions.get("window").width / 2,
    backgroundColor: "#f2f2f2",
    padding: 10,
    flex: 1,
    paddingBottom: 5,
    paddingTop: 15,
  },
  AddBtnTouchable: {
    backgroundColor: YELLOW_COLOR_CODE,
    width: "100%",
    marginVertical: 5,
    height: 30,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  HeaderArrow: {
    paddingHorizontal: 20,
    justifyContent: "center",
    alignItems: "flex-start",
    paddingLeft: 10,
  },
  HeaderViewMidle: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  HeaderMiddleTxt: {
    color: WHITE_COLOR_CODE,
    fontFamily: FONT_FAMILY_BOLD,
    fontSize: 18,
  },
  FilterImgeView: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  filterVw: {
    flex: 1,
    marginTop: 20,
    paddingHorizontal: 20,
  },
  container: {
    height: 50,
    borderColor: "#d8d8d8",
    borderBottomWidth: 2,
    borderRadius: 12,
    flexDirection: "row",
    marginTop: 15,
  },
  pickerVw: {
    paddingHorizontal: 20,
    backgroundColor: WHITE_COLOR_CODE,
    marginLeft: 8,
    fontFamily: FONT_FAMILY_REGULAR,
    fontSize: 17,
  },
});
export default Styles;
