require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'AbbyPages' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'


  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'AbbyPagesTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'AbbyPages-tvOS' do
  # Pods for AbbyPages-tvOS

  target 'AbbyPages-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
